version: '3.3'
services:
  nginx:
    restart: always
    build:
      context: nginx
      args:
        VERSION: "${VERSION}"
        DOJO_HOST: "${DOJO_HOST}"
    ports:
    - "80:80"
    - "443:443"
    environment:
    - DH_SIZE=512
    depends_on:
    - dojo
    links:
    - dojo
  dojo:
    restart: always
    build:
      context: dojo
      args:
        VERSION: "${VERSION}"
    volumes:
      - "./static:/opt/django-DefectDojo/static"
    ports:
    - "8000:8000"
    environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=defectdojo
    - MYSQL_USER=defectdojo
    - MYSQL_PASSWORD=defectdojo

    - ALLOWED_HOSTS='0.0.0.0'
    - HOST=0.0.0.0
    - LOAD_SAMPLE_DATA=False
    - GENERATE_STATIC_FILES=True
    - DD_ADMIN_USER=admin \
    - DD_ADMIN_MAIL=admin@defectdojo.local \
    - DD_ADMIN_PASSWORD='' \
    - DD_ADMIN_FIRST_NAME=Administrator \
    - DD_ADMIN_LAST_NAME=User \
    - DD_ALLOWED_HOSTS="*" \
    # - DD_CELERY_BEAT_SCHEDULE_FILENAME="/run/celery-beat-schedule" \
    # - DD_CELERY_BROKER_SCHEME="amqp" \
    # - DD_CELERY_BROKER_USER="defectdojo" \
    # - DD_CELERY_BROKER_PASSWORD="defectdojo" \
    # - DD_CELERY_BROKER_HOST="rabbitmq" \
    # - DD_CELERY_BROKER_PORT="5672" \
    # - DD_CELERY_BROKER_PATH="//" \
    # - DD_CELERY_LOG_LEVEL="INFO" \
    - DD_DATABASE_ENGINE="django.db.backends.mysql" \
    - DD_DATABASE_HOST="mysql" \
    - DD_DATABASE_NAME="defectdojo" \
    - DD_DATABASE_PASSWORD="defectdojo" \
    - DD_DATABASE_PORT="3306" \
    - DD_DATABASE_USER="defectdojo" \
    - DD_DATABASE_URL=${DD_DATABASE_URL:-mysql://defectdojo:defectdojo@mysql:3306/defectdojo}
    - DD_INITIALIZE=true \
    - DD_UWSGI_MODE="socket" \
    - DD_UWSGI_ENDPOINT="0.0.0.0:3031" \
    - DD_DJANGO_ADMIN_ENABLED="True" \
    - DD_TRACK_MIGRATIONS="True" \
    - DD_DJANGO_METRICS_ENABLED="False"
  mysql:
    restart: always
    image: mysql:5.7
    ports:
    - "3306"
    environment:
    - DOJO_MYSQL_HOST=mysql
    - DOJO_MYSQL_PORT=3306
    - MYSQL_DATABASE=defectdojo
    - MYSQL_USER=defectdojo
    - MYSQL_PASSWORD=defectdojo
    - MYSQL_ROOT_PASSWORD=defectdojo
    - max_allowed_packet=16M